### ISSUE TITLE
Atomic has been deprecated

### ISSUE THREAD

**Issue by diegodurs** [groupon/locality-uuid.rb#2]
```
Post-install message from atomic:
This gem has been deprecated and merged into Concurrent Ruby (http://concurrent-ruby.com)
```

cc @gregory

**Comment by bakks** [comment]
@diegodurs thanks for the heads up! This should be fixed by changes in https://github.com/groupon/locality-uuid.rb/pull/3, which I've already pushed to Rubygems as [v1.2.0](https://rubygems.org/gems/locality-uuid).

**Comment by diegodurs** [comment]
cool! thanks
